# download 线程状态常量
STATUS_INIT = 0
STATUS_READY = 1
STATUS_RUNNING = 2
STATUS_WORK_FINISHED = 3
STATUS_EXIT = 4
STATUS_FORCE_EXIT = 5
STATUS_PAUSE = 6

# 对 download 过程中的 getsize 约束程度
LEVEL_ENFORCE = 10     # 绝对精准，精准至byte级别
LEVEL_PERMISSIVE = 11  # 宽松，达量即可，允许超量

# downloader 任务状态
DL_FIRST_BORN = 20
DL_INITIATING = 21
DL_RUNNING = 22
DL_COMPLETE = 23
DL_FAILED = 29

# scanner deep level
SCAN_NORMAL = 30
SCAN_MORE_DEEPER = 31
SCAN_DEEPEST = 32

